In [ ]:
# from <module_name> import <name>
# contoh
# from pkg<nama_folder>.mod1<nama_file> import port<nama_function>

In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
!conda list

# packages in environment at C:\Users\BRI\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
anaconda                  2019.10                  py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.7                    py37_0  
anaconda-project          0.8.3                      py_0  
asn1crypto                1.0.1                    py37_0  
astroid                   2.3.1                    py37_0  
astropy                   3.2.1            py37he774522_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.2.0                     py_0  
babel                     2.7.0                      py_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.5     

In [6]:
!conda --version
!conda list numpy

conda 4.7.12
# packages in environment at C:\Users\BRI\Anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.16.5           py37h19fb1c0_0  
numpy-base                1.16.5           py37hc3f5095_0  
numpydoc                  0.9.1                      py_0  


In [11]:
np.__version__

'1.16.5'

In [10]:
!pip install numpy --upgrade

  Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:
      Successfully uninstalled numpy-1.16.5


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\users\\bri\\anaconda3\\lib\\site-packages\\~umpy\\core\\_multiarray_tests.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



##array

In [36]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='int64')
print(arr1)
type(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


numpy.ndarray

In [19]:
print(arr1[0])
print(arr1[-1])

[1 2 3]
[10 11 12]


In [21]:
# list tidak berbentuk matriks
# kalau array berbentuk matriks
list1 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


In [23]:
list1[0][0]

1

In [30]:
print(arr1[0,0])
#list1[0,0] tidak bisa
print(arr1[:,0]) #column
list1[0][0],list1[1][0],list1[2][0],list1[3][0]

1
[ 1  4  7 10]


(1, 4, 7, 10)

In [37]:
arr1.dtype, type(arr1)

(dtype('int64'), numpy.ndarray)

In [35]:
arr2 = np.array([[.1,.2],[.3,.4]])
print(arr2)
arr2.dtype, type(arr2)

[[0.1 0.2]
 [0.3 0.4]]


(dtype('float64'), numpy.ndarray)

In [42]:
arr3 = np.array([
    [
        [1,2,3],
        [11,22,33]
    ],
    [
        [4,5,6],
        [44,55,66]
    ]
])

In [43]:
print(arr3)

[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]]


In [45]:
# shape of array
print("Shape of array1: ", arr1.shape)
print("Shape of array2: ", arr2.shape)
print("Shape of array3: ", arr3.shape)

# dimension of array
print("Dimension of arr1 : ", arr1.ndim)
print("Dimension of arr2 : ", arr2.ndim)
print("Dimension of arr3 : ", arr3.ndim)

Shape of array1:  (4, 3)
Shape of array2:  (2, 2)
Shape of array3:  (2, 2, 3)
Dimension of arr1 :  2
Dimension of arr2 :  2
Dimension of arr3 :  3


In [ ]:
#array cuma bisa 1 tipe data
#array ukurannya harus sama

In [46]:
np.array()
np.zeros() # membuat array semua elemennya 0
np.ones() # membuat array semua elemennya 1
np.empty() # membuat array dengan bilangan random
np.arrange() #membuat array dengan bilangan random

TypeError: array() missing required argument 'object' (pos 1)

In [56]:
arr_zero_1 = np.zeros(2)
arr_zero_2 = np.zeros([5,2])
arr_zero_3 = np.zeros([5,2,2])

In [59]:
print(arr_zero_1,arr_zero_1.shape)
print(arr_zero_2, arr_zero_2.shape)
print(arr_zero_3,arr_zero_3.shape)

[0. 0.] (2,)
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] (5, 2)
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]] (5, 2, 2)


In [61]:
arr_ones_1 = np.ones(2)
arr_ones_2 = np.ones([5,2])
arr_ones_3 = np.ones([5,2,2])

In [62]:
print(arr_ones_1,arr_ones_1.shape)
print(arr_ones_2, arr_ones_2.shape)
print(arr_ones_3,arr_ones_3.shape)

[1. 1.] (2,)
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] (5, 2)
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]] (5, 2, 2)


In [69]:
arr_empty = np.empty([7,4])

In [70]:
print(arr_empty)

[[1.18422812e-311 9.23902758e-322 0.00000000e+000 0.00000000e+000]
 [1.18407365e-311 5.02034658e+175 3.08736282e-057 1.71636565e+185]
 [9.58732564e-043 6.12122583e+169 5.01163191e+217 5.49419094e-143]
 [1.50008929e+248 1.06396443e+224 1.47765135e+248 4.30625279e-096]
 [9.08366793e+223 2.10546825e-076 4.47042317e-033 4.91147188e-062]
 [3.69484292e-057 2.24729311e+174 1.56605686e-076 9.15558394e-072]
 [4.17265870e-057 7.49548297e-067 1.28625693e+248 4.24948967e-086]]


In [74]:
array = np.arange(0,10)

In [75]:
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# add, remove, sort

In [77]:
arr_one = np.array([1,2,3,4,5])
arr_one

array([1, 2, 3, 4, 5])

In [78]:
np.append(arr_one,10)
# axis = 1 

array([ 1,  2,  3,  4,  5, 10])

In [79]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int64)

In [84]:
# arr4 = np.
np.append(arr1, [[13,14,15]], axis=0)
# axis = 0 menambah baris

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]], dtype=int64)

In [87]:
np.append(arr1, np.array([[13],[14],[15],[16]]), axis=1)
# axis = 1 menambah kolom

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15],
       [10, 11, 12, 16]], dtype=int64)

In [97]:
np.append(arr_ones_3,np.array([[[10,11],[12,13],[14,15],[16,17],[18,19]],[10,11],[12,13],[14,15],[16,17],[18,19]]),axis=1)

ValueError: all the input arrays must have same number of dimensions

In [88]:
arr_ones_3.shape

(5, 2, 2)

In [98]:
np.array([[[10,11],[12,13],[14,15],[16,17],[18,19]],
          [[10,11],[12,13],[14,15],[16,17],[18,19]]]).shape

(2, 5, 2)

In [93]:
arr_12 = np.arange(12)
print(arr_12)
print(arr_12+1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [104]:
print(arr1)
print(arr1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [107]:
np.delete(arr1,0,axis=1)
# menghapus kolom kedua

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]], dtype=int64)

In [100]:
np.delete(arr1,1,axis=0)
#menghapus baris ke-1

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int64)

In [108]:
# digunakan untuk mengurutkan
np.sort(arr3)

array([[[ 1,  2,  3],
        [11, 22, 33]],

       [[ 4,  5,  6],
        [44, 55, 66]]])

In [111]:
arr1[0] = [5,11,10]
arr1

array([[ 5, 11, 10],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int64)

In [112]:
print(np.sort(arr1))
print(np.sort(arr1,axis=0))

[[ 5 10 11]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [ 5  8  9]
 [ 7 11 10]
 [10 11 12]]


In [115]:
arr1.shape

(4, 3)

In [116]:
# perbedaan vector kolom dan baris
vector_baris = np.array([1,2,3,4,5])
print(vector_baris, vector_baris.shape)
vector_col = np.array([[1],[2],[3],[4],[5]])
print(vector_col, vector_col.shape)

[1 2 3 4 5] (5,)
[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)


In [123]:
print("normal :",arr1)
print("reshape : ",np.reshape(arr1,(3,4)))

normal : [[ 5 11 10]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
reshape :  [[ 5 11 10  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [125]:
arr1[:,:,np.newaxis].shape

(4, 3, 1)

In [126]:
arr1[arr1>5]

array([11, 10,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [127]:
# mengambil elemen bilangan genap
arr1[arr1 % 2 == 0]

array([10,  4,  6,  8, 10, 12], dtype=int64)

In [129]:
# mengambil elemen bilangan genap
arr1[(arr1 % 2 == 0) | (arr1 % 3 == 0)]

array([10,  4,  6,  8,  9, 10, 12], dtype=int64)

In [130]:
print(arr1)
print(arr1.sum(axis=0))
print(arr1.sum(axis=1))

[[ 5 11 10]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[26 35 37]
[26 15 24 33]


In [131]:
print(arr1.std(),arr1.mean(),arr1.min())

2.6087459737497545 8.166666666666666 4


In [134]:
arr11 = arr1*2
print(arr1)
print(arr11)

[[ 5 11 10]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[10 22 20]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [139]:
print(arr1+arr11)
print(arr1*arr11)
print(np.multiply(arr1,arr11))

[[15 33 30]
 [12 15 18]
 [21 24 27]
 [30 33 36]]
[[ 50 242 200]
 [ 32  50  72]
 [ 98 128 162]
 [200 242 288]]
[[ 50 242 200]
 [ 32  50  72]
 [ 98 128 162]
 [200 242 288]]


In [136]:
arr1.dot(arr11.T)

array([[492, 270, 426, 582],
       [270, 154, 244, 334],
       [426, 244, 388, 532],
       [582, 334, 532, 730]], dtype=int64)

In [37]:
arr_kuis = np.arange(0,1,0.05)[:, None]
print(arr_kuis,arr_kuis.shape)

[[0.  ]
 [0.05]
 [0.1 ]
 [0.15]
 [0.2 ]
 [0.25]
 [0.3 ]
 [0.35]
 [0.4 ]
 [0.45]
 [0.5 ]
 [0.55]
 [0.6 ]
 [0.65]
 [0.7 ]
 [0.75]
 [0.8 ]
 [0.85]
 [0.9 ]
 [0.95]] (20, 1)


In [31]:
arr_kuis_reshape = np.reshape(arr_kuis,(10,2))
print(arr_kuis_reshape)

[[0.   0.05]
 [0.1  0.15]
 [0.2  0.25]
 [0.3  0.35]
 [0.4  0.45]
 [0.5  0.55]
 [0.6  0.65]
 [0.7  0.75]
 [0.8  0.85]
 [0.9  0.95]]


In [32]:
arr_kuis_reshape_2_times = 2*arr_kuis_reshape

In [35]:
print(arr_kuis_reshape_2_times,arr_kuis_reshape_2_times.shape)

[[0.  0.1]
 [0.2 0.3]
 [0.4 0.5]
 [0.6 0.7]
 [0.8 0.9]
 [1.  1.1]
 [1.2 1.3]
 [1.4 1.5]
 [1.6 1.7]
 [1.8 1.9]] (10, 2)


In [39]:
transpose = arr_kuis_reshape_2_times.T
print(transpose, transpose.shape)

[[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
 [0.1 0.3 0.5 0.7 0.9 1.1 1.3 1.5 1.7 1.9]] (2, 10)


In [44]:
mm = np.matmul(arr_kuis, transpose)
# transpose = arr_kuis_reshape_2_times.T
print(mm)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [26]:
mm_mean = transpose.mean(axis = 0)
print(mm_mean)

[0.05 0.25 0.45 0.65 0.85 1.05 1.25 1.45 1.65 1.85]


In [42]:
mm_median = np.median(transpose,axis = 0)
print(mm_median)
transpose.std(axis=0), transpose.var(axis = 0)

[0.05 0.25 0.45 0.65 0.85 1.05 1.25 1.45 1.65 1.85]


(array([0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]),
 array([0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025, 0.0025,
        0.0025, 0.0025]))

In [61]:
# digunakan untuk tetap menyamakan nilai random apabila di refresh
np.random.seed(0)
rand_int = np.random.randint(5,10, size=(3,2))
rand_uniform = np.random.uniform(10,50, size=(3,2))
# sesuai parameter distribusi normal sesuai dengan rata-rata dan std
# 1. untuk rata-rata 5. std
rand_normal = np.random.normal(1.,5., size=(3,2))

In [62]:
print(rand_int)
print(rand_uniform)
print(rand_normal)

[[9 5]
 [8 8]
 [8 6]]
[[34.94254787 25.37526829]
 [21.90138426 12.26851909]
 [20.90625178 29.10660469]]
[[ 0.56163466  7.83439683]
 [ 6.62657052 -0.79497776]
 [ 7.10304049 -5.69747775]]
